// Resolves one Unsplash photo per product by actually searching for it, rather
// than hard-coding photo IDs from memory (which silently yields a landscape shot
// on a headphones card). Output is checked in as src/data/images.js; this script
// only needs re-running when the catalogue changes.
//
// Three things this has to work around:
//   - node's fetch gets served a bot challenge (401); curl's TLS fingerprint passes
//   - the search page is ~600KB and curl often hits --max-time mid-stream, but the
//     <head> preloads the top results in rank order, so a partial body is enough
//     (the bytes received so far arrive on err.stdout)
//   - no shell: a POSIX pipeline isn't portable on Windows
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const QUERIES = {
  'bz-1001': 'over ear headphones',
  'bz-1002': 'wireless earbuds',
  'bz-1003': 'laptop computer',
  'bz-1004': 'smartphone',
  'bz-1005': 'mirrorless camera',
  'bz-1006': 'bookshelf speaker',
  'bz-1007': 'mechanical keyboard',
  'bz-1008': 'computer monitor',
  'bz-2001': 'electric kettle',
  'bz-2002': 'dutch oven cast iron pot',
  'bz-2003': 'floor lamp',
  'bz-2004': 'ceramic planter',
  'bz-2005': 'chef knife',
  'bz-2006': 'wool blanket',
  'bz-3001': 'hardcover book',
  'bz-3002': 'stack of books',
  'bz-3003': 'cookbook',
  'bz-3004': 'paperback book',
  'bz-4001': 'running shoes',
  'bz-4002': 'canvas jacket',
  'bz-4003': 'wrist watch',
  'bz-4004': 'backpack',
  'bz-5001': 'hiking backpack',
  'bz-5002': 'insulated water bottle',
  'bz-5003': 'yoga mat',
  'bz-5004': 'trekking poles',
  'bz-6001': 'office chair',
  'bz-6002': 'standing desk',
  'bz-6003': 'notebook stationery',
  'bz-6004': 'desk lamp',
};

// Only images.unsplash.com: plus.unsplash.com hits are Unsplash+ premium and not
// freely usable.
const RE = /images\.unsplash\.com\/(photo-[a-zA-Z0-9_-]+)/g;

function idsFor(query) {
  return new Promise((resolve) => {
    const url = `https://unsplash.com/s/photos/${encodeURIComponent(query)}`;
    execFile(
      'curl',
      ['-s', '--max-time', '12', url],
      { encoding: 'utf8', maxBuffer: 80 * 1024 * 1024 },
      (err, stdout) => {
        const html = stdout || (err && err.stdout) || '';
        resolve([...new Set([...html.matchAll(RE)].map((m) => m[1]))]);
      }
    );
  });
}

async function pool(entries, size, worker) {
  const results = [];
  let i = 0;
  await Promise.all(
    Array.from({ length: size }, async () => {
      while (i < entries.length) {
        const idx = i++;
        results[idx] = await worker(entries[idx]);
      }
    })
  );
  return results;
}

(async () => {
  const entries = Object.entries(QUERIES);
  const lists = await pool(entries, 8, async ([id, query]) => {
    const ids = await idsFor(query);
    console.log(`${id}  ${query.padEnd(26)} ${ids.length} candidate(s)`);
    return ids;
  });

  // Assign greedily so no two products share a photo.
  const used = new Set();
  const out = {};
  const unresolved = [];
  entries.forEach(([id, query], idx) => {
    const pick = (lists[idx] || []).find((p) => !used.has(p));
    if (pick) {
      used.add(pick);
      out[id] = pick;
    } else {
      unresolved.push(`${id} (${query})`);
    }
  });

  const file = `// Generated by scripts/fetch-images.cjs — one Unsplash photo per product,
// resolved by searching for the product rather than hard-coding IDs.
// Re-run \`node scripts/fetch-images.cjs\` after changing the catalogue.

export const PHOTO_IDS = ${JSON.stringify(out, null, 2)};

// Unsplash serves every derivative from the same URL, so one source covers all sizes.
// fm=webp and q=72 keep cards light; crop=entropy centres on the subject.
export function photoUrl(productId, width = 600) {
  const id = PHOTO_IDS[productId];
  if (!id) return null;
  return \`https://images.unsplash.com/\${id}?auto=format&fit=crop&crop=entropy&w=\${width}&h=\${width}&q=72&fm=webp\`;
}

export function photoSrcSet(productId) {
  const id = PHOTO_IDS[productId];
  if (!id) return null;
  return [300, 600, 900].map((w) => \`\${photoUrl(productId, w)} \${w}w\`).join(', ');
}
`;

  fs.writeFileSync(path.join(__dirname, '..', 'src', 'data', 'images.js'), file, 'utf8');
  console.log(`\nresolved ${Object.keys(out).length}/${entries.length}`);
  if (unresolved.length) console.log('unresolved:', unresolved.join(', '));
})();
